"""" This file contains the functions to apply to the columns of the datasets and concatenated dataframe. """

import re


def get_columns(year):
    """ Get the columns of the datasets based on the year. """
    columns = list()
    
    if year == '2015':
        columns = ['country', 'region', 'happiness_rank', 'happiness_score', 'standard_error', 'economy_per_capita', 'family', 'life_expectancy', 'freedom', 'government_corruption', 'generosity', 'dystopia_residual', 'year']
    if year == '2016':
        columns = ['country', 'region', 'happiness_rank', 'happiness_score', 'lower_confidence_interval', 'upper_confidence_interval', 'economy_per_capita', 'family', 'life_expectancy', 'freedom', 'government_corruption', 'generosity', 'dystopia_residual', 'year']
    if year == '2017':
        columns = ['country', 'happiness_rank', 'happiness_score', 'whisker_high', 'whisker_low', 'economy_per_capita', 'family', 'life_expectancy', 'freedom','generosity', 'government_corruption',  'dystopia_residual', 'year']
    if year == '2018':
        columns = ['happiness_rank', 'country_region', 'happiness_score', 'economy_per_capita', 'family', 'life_expectancy', 'freedom', 'generosity', 'government_corruption', 'year']
    if year == '2019':
        columns = ['happiness_rank', 'country_region', 'happiness_score', 'economy_per_capita', 'family', 'life_expectancy', 'freedom', 'generosity', 'government_corruption', 'year']
        
    return columns

def get_region_by_country():
    """ Get the region based on the country. """
    country_region_dict = {
        'Finland': 'Europe',
        'Norway': 'Europe',
        'Denmark': 'Europe',
        'Iceland': 'Europe',
        'Switzerland': 'Europe',
        'Netherlands': 'Europe',
        'Canada': 'North America',
        'New Zealand': 'Oceania',
        'Sweden': 'Europe',
        'Australia': 'Oceania',
        'United Kingdom': 'Europe',
        'Austria': 'Europe',
        'Costa Rica': 'Central America',
        'Ireland': 'Europe',
        'Germany': 'Europe',
        'Belgium': 'Europe',
        'Luxembourg': 'Europe',
        'United States': 'North America',
        'Israel': 'Middle East',
        'United Arab Emirates': 'Middle East',
        'Czech Republic': 'Europe',
        'Malta': 'Europe',
        'France': 'Europe',
        'Mexico': 'Latin America and Caribbean',
        'Chile': 'South America',
        'Taiwan': 'Eastern Asia',
        'Panama': 'Central America',
        'Brazil': 'South America',
        'Argentina': 'South America',
        'Guatemala': 'Central America',
        'Uruguay': 'South America',
        'Qatar': 'Middle East',
        'Saudi Arabia': 'Middle East',
        'Singapore': 'Southeastern Asia',
        'Malaysia': 'Southeastern Asia',
        'Spain': 'Europe',
        'Colombia': 'South America',
        'Trinidad & Tobago': 'Latin America and Caribbean',
        'Slovakia': 'Central and Eastern Europe',
        'El Salvador': 'Central America',
        'Nicaragua': 'Central America',
        'Poland': 'Central and Eastern Europe',
        'Bahrain': 'Middle East',
        'Uzbekistan': 'Central Asia',
        'Kuwait': 'Middle East',
        'Thailand': 'Southeastern Asia',
        'Italy': 'Europe',
        'Ecuador': 'South America',
        'Belize': 'Central America',
        'Lithuania': 'Central and Eastern Europe',
        'Slovenia': 'Central and Eastern Europe',
        'Romania': 'Central and Eastern Europe',
        'Latvia': 'Central and Eastern Europe',
        'Japan': 'Eastern Asia',
        'Mauritius': 'Sub-Saharan Africa',
        'Jamaica': 'Latin America and Caribbean',
        'South Korea': 'Eastern Asia',
        'Northern Cyprus': 'Western Europe',
        'Russia': 'Europe',
        'Kazakhstan': 'Central Asia',
        'Cyprus': 'Western Europe',
        'Bolivia': 'South America',
        'Estonia': 'Northern Europe',
        'Paraguay': 'South America',
        'Peru': 'South America',
        'Kosovo': 'Europe',
        'Moldova': 'Europe',
        'Turkmenistan': 'Central Asia',
        'Hungary': 'Central and Eastern Europe',
        'Libya': 'Middle East and Northern Africa',
        'Philippines': 'Southeastern Asia',
        'Honduras': 'Central America',
        'Belarus': 'Central and Eastern Europe',
        'Turkey': 'Middle East',
        'Pakistan': 'Southern Asia',
        'Hong Kong': 'Eastern Asia',
        'Portugal': 'Europe',
        'Serbia': 'Central and Eastern Europe',
        'Greece': 'Europe',
        'Lebanon': 'Middle East',
        'Montenegro': 'Central and Eastern Europe',
        'Croatia': 'Central and Eastern Europe',
        'Dominican Republic': 'Latin America and Caribbean',
        'Algeria': 'Middle East and Northern Africa',
        'Morocco': 'Middle East and Northern Africa',
        'China': 'Eastern Asia',
        'Azerbaijan': 'Central Asia',
        'Tajikistan': 'Central Asia',
        'Macedonia': 'Central and Eastern Europe',
        'Jordan': 'Middle East',
        'Nigeria': 'Sub-Saharan Africa',
        'Kyrgyzstan': 'Central Asia',
        'Bosnia and Herzegovina': 'Central and Eastern Europe',
        'Mongolia': 'Eastern Asia',
        'Vietnam': 'Southeastern Asia',
        'Indonesia': 'Southeastern Asia',
        'Bhutan': 'Southern Asia',
        'Somalia': 'Sub-Saharan Africa',
        'Cameroon': 'Sub-Saharan Africa',
        'Bulgaria': 'Central and Eastern Europe',
        'Nepal': 'Southern Asia',
        'Venezuela': 'Latin America and Caribbean',
        'Gabon': 'Sub-Saharan Africa',
        'Palestinian Territories': 'Middle East and Northern Africa',
        'South Africa': 'Sub-Saharan Africa',
        'Iran': 'Middle East',
        'Ivory Coast': 'Sub-Saharan Africa',
        'Ghana': 'Sub-Saharan Africa',
        'Senegal': 'Sub-Saharan Africa',
        'Laos': 'Southeastern Asia',
        'Tunisia': 'Middle East and Northern Africa',
        'Albania': 'Central and Eastern Europe',
        'Sierra Leone': 'Sub-Saharan Africa',
        'Congo (Brazzaville)': 'Sub-Saharan Africa',
        'Bangladesh': 'Southern Asia',
        'Sri Lanka': 'Southern Asia',
        'Iraq': 'Middle East',
        'Mali': 'Sub-Saharan Africa',
        'Namibia': 'Sub-Saharan Africa',
        'Cambodia': 'Southeastern Asia',
        'Burkina Faso': 'Sub-Saharan Africa',
        'Egypt': 'Middle East and Northern Africa',
        'Mozambique': 'Sub-Saharan Africa',
        'Kenya': 'Sub-Saharan Africa',
        'Zambia': 'Sub-Saharan Africa',
        'Mauritania': 'Sub-Saharan Africa',
        'Ethiopia': 'Sub-Saharan Africa',
        'Georgia': 'Central and Eastern Europe',
        'Armenia': 'Central and Eastern Europe',
        'Myanmar': 'Southeastern Asia',
        'Chad': 'Sub-Saharan Africa',
        'Congo (Kinshasa)': 'Sub-Saharan Africa',
        'India': 'Southern Asia',
        'Niger': 'Sub-Saharan Africa',
        'Uganda': 'Sub-Saharan Africa',
        'Benin': 'Sub-Saharan Africa',
        'Sudan': 'Sub-Saharan Africa',
        'Ukraine': 'Central and Eastern Europe',
        'Togo': 'Sub-Saharan Africa',
        'Guinea': 'Sub-Saharan Africa',
        'Lesotho': 'Sub-Saharan Africa',
        'Angola': 'Sub-Saharan Africa',
        'Madagascar': 'Sub-Saharan Africa',
        'Zimbabwe': 'Sub-Saharan Africa',
        'Afghanistan': 'Southern Asia',
        'Botswana': 'Sub-Saharan Africa',
        'Malawi': 'Sub-Saharan Africa',
        'Haiti': 'Latin America and Caribbean',
        'Liberia': 'Sub-Saharan Africa',
        'Syria': 'Middle East',
        'Rwanda': 'Sub-Saharan Africa',
        'Yemen': 'Middle East',
        'Tanzania': 'Sub-Saharan Africa',
        'South Sudan': 'Sub-Saharan Africa',
        'Central African Republic': 'Sub-Saharan Africa',
        'Burundi': 'Sub-Saharan Africa',
        'North Macedonia': 'Central and Eastern Europe',
        'Gambia': 'Sub-Saharan Africa',
        'Swaziland': 'Sub-Saharan Africa',
        'Comoros': 'Sub-Saharan Africa'
    }
    
    return country_region_dict